In [1]:
from google.colab import drive

# Autoriser l'accès à Google Drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [15]:
import pandas as pd, io, re
from pathlib import Path

chemin = Path('/content/drive/MyDrive/Manal El ghafiri- Soha El ghamri Fin 2 Tp2/FMI.xls')
if not chemin.is_file():
    raise FileNotFoundError(f'Fichier introuvable : {chemin}')

# 1) lire le texte (essayer plusieurs encodages)
texte = None
for enc in ('utf-8-sig', 'utf-16', 'cp1252', 'latin-1'):
    try:
        texte = chemin.read_text(encoding=enc)
        break
    except UnicodeError:
        continue

lignes = [l for l in texte.splitlines() if l.strip()]

# 2) trouver la ligne d'en-tête (celle qui commence par "Date")
i_entete = next(i for i, l in enumerate(lignes) if l.strip().startswith('Date'))

# 3) garder seulement les lignes de données ("Mois jj, aaaa")
motif = re.compile(r'^\s*[A-Z][a-z]+ \d{1,2}, \d{4}\t')
donnees = [l for l in lignes[i_entete + 1:] if motif.match(l)]

df = pd.read_csv(io.StringIO('\n'.join([lignes[i_entete]] + donnees)),
                 sep='\t', thousands=',')
df.columns = ['date', 'titres', 'compte_1', 'compte_2', 'cva', 'cva_2', 'total']

df['date'] = pd.to_datetime(df['date'].str.strip(), format='%B %d, %Y')
df['annee'] = df['date'].dt.year

display(df.head(10))
print('Dimensions :', df.shape)

,date,titres,compte_1,compte_2,cva,cva_2,total,annee
0,2025-09-30,767434350,19929540,475158,-43048809,0,744790239,2025
1,2024-12-31,724385541,557629540,475158,0,0,1282490239,2024
2,2023-12-31,724385541,1519729540,876477,0,0,2244991558,2023
3,2022-12-31,724385541,1522462451,63035,0,0,2246911027,2022
4,2021-12-31,724385541,1522462451,67725,0,0,2246915717,2021
5,2020-12-31,724385541,2173462451,72644,0,1,2897920637,2020
6,2019-12-31,732687201,14360791,74704,0,0,747122696,2019
7,2018-12-31,732687201,14360791,79250,0,0,747127242,2018
8,2017-12-31,732687201,14692637,2943,0,0,747382781,2017
9,2016-12-31,732687201,14700011,8806,0,0,747396018,2016

Dimensions : (42, 8)

In [16]:
import sqlite3
import pandas as pd

conn = sqlite3.connect(':memory:')
df.to_sql('avoirs_fmi', conn, index=False, if_exists='replace')

def executer_sql(titre, requete):
    print(f"=== {titre} ===")
    display(pd.read_sql_query(requete, conn))
    print("\n")

# 1. Toutes les observations
executer_sql("1. Toutes les observations", "SELECT * FROM avoirs_fmi;")

# 2. Choix de colonnes + calcul : part des titres dans le total
executer_sql("2. Part des titres dans le total", """
SELECT annee, titres, total,
       ROUND(titres * 100.0 / total, 1) AS part_titres_pct
FROM avoirs_fmi;
""")

# 3. LIMIT : les 3 années les plus récentes
executer_sql("3. Les 3 années les plus récentes", """
SELECT annee, total FROM avoirs_fmi
ORDER BY annee DESC
LIMIT 3;
""")

# 4. ORDER BY : classement selon le compte n°1
executer_sql("4. Tri selon le compte n°1 (décroissant)", """
SELECT annee, compte_1
FROM avoirs_fmi
ORDER BY compte_1 DESC;
""")

# 5. WHERE : années où le total est inférieur à 600 millions
executer_sql("5. Années où le total est inférieur à 600 millions de DTS", """
SELECT annee, total FROM avoirs_fmi
WHERE total < 600000000
ORDER BY annee;
""")

# 6. COUNT : nombre d'années où le total dépasse 1 milliard
executer_sql("6. Nombre d'années avec un total > 1 milliard de DTS", """
SELECT COUNT(*) AS nb_annees FROM avoirs_fmi
WHERE total > 1000000000;
""")

# 7. AVG : moyenne des titres depuis 2010
executer_sql("7. Moyenne des titres depuis 2010", """
SELECT ROUND(AVG(titres)) AS moyenne_titres
FROM avoirs_fmi
WHERE annee >= 2010;
""")

# 8. MIN / MAX des titres
executer_sql("8. Minimum et maximum des titres", """
SELECT MIN(titres) AS min_titres, MAX(titres) AS max_titres
FROM avoirs_fmi;
""")

# 9. GROUP BY : périodes de 5 ans
executer_sql("9. Moyenne du total par période de 5 ans", """
SELECT (annee/5)*5 AS debut_periode,
       COUNT(*) AS nb_annees,
       ROUND(AVG(total)) AS total_moyen
FROM avoirs_fmi
GROUP BY debut_periode
ORDER BY debut_periode;
""")

# 10. HAVING : périodes où le compte n°1 a dépassé 1 milliard
executer_sql("10. Périodes de 5 ans où le compte n°1 a dépassé 1 milliard", """
SELECT (annee/5)*5 AS debut_periode,
       MAX(compte_1) AS max_compte_1
FROM avoirs_fmi
GROUP BY debut_periode
HAVING MAX(compte_1) > 1000000000
ORDER BY debut_periode;
""")

# 11. AND / OR
executer_sql("11. AND : depuis 2000 et total inférieur à 600 millions", """
SELECT annee, total FROM avoirs_fmi
WHERE annee >= 2000 AND total < 600000000
ORDER BY annee;
""")

executer_sql("11. OR : total > 2 milliards OU compte CVA négatif", """
SELECT annee, cva, total FROM avoirs_fmi
WHERE total > 2000000000 OR cva < 0
ORDER BY annee;
""")

# 12. BETWEEN et IN
executer_sql("12. BETWEEN : période 2015-2019", """
SELECT annee, total FROM avoirs_fmi
WHERE annee BETWEEN 2015 AND 2019
ORDER BY annee;
""")

executer_sql("12. IN : années choisies", """
SELECT annee, total FROM avoirs_fmi
WHERE annee IN (1987, 1998, 2008, 2020, 2025)
ORDER BY annee;
""")

# 13. RANK : classement selon le compte n°1
executer_sql("13. Classement des 8 plus hauts niveaux du compte n°1", """
SELECT annee, compte_1,
       RANK() OVER (ORDER BY compte_1 DESC) AS rang
FROM avoirs_fmi
ORDER BY rang
LIMIT 8;
""")

# 14. Sous-requête : années sous la moyenne
executer_sql("14. Années où le total est sous la moyenne", """
SELECT annee, total
FROM avoirs_fmi
WHERE total < (SELECT AVG(total) FROM avoirs_fmi)
ORDER BY annee;
""")

# 15. Synthèse : tendance annuelle (hausse / baisse)
executer_sql("15. Synthèse : tendance du total d'une année à l'autre", """
SELECT annee, total, variation,
  CASE WHEN variation IS NULL THEN 'Départ'
       WHEN variation > 0 THEN 'Hausse'
       WHEN variation < 0 THEN 'Baisse'
       ELSE 'Stable' END AS tendance
FROM (
    SELECT annee, total,
           total - LAG(total) OVER (ORDER BY annee) AS variation
    FROM avoirs_fmi
)
ORDER BY annee DESC;
""")

=== 1. Toutes les observations ===

,date,titres,compte_1,compte_2,cva,cva_2,total,annee
0,2025-09-30 00:00:00,767434350,19929540,475158,-43048809,0,744790239,2025
1,2024-12-31 00:00:00,724385541,557629540,475158,0,0,1282490239,2024
2,2023-12-31 00:00:00,724385541,1519729540,876477,0,0,2244991558,2023
3,2022-12-31 00:00:00,724385541,1522462451,63035,0,0,2246911027,2022
4,2021-12-31 00:00:00,724385541,1522462451,67725,0,0,2246915717,2021
5,2020-12-31 00:00:00,724385541,2173462451,72644,0,1,2897920637,2020
6,2019-12-31 00:00:00,732687201,14360791,74704,0,0,747122696,2019
7,2018-12-31 00:00:00,732687201,14360791,79250,0,0,747127242,2018
8,2017-12-31 00:00:00,732687201,14692637,2943,0,0,747382781,2017
9,2016-12-31 00:00:00,732687201,14700011,8806,0,0,747396018,2016
10,2015-12-31 00:00:00,503037201,14700011,8806,0,0,517746018,2015
11,2014-12-31 00:00:00,503037201,14700011,8806,0,0,517746018,2014
12,2013-12-31 00:00:00,503037201,14711948,1712,0,0,517750861,2013
13,2012-12-31 00:00:00,503037201,14711948,1712,0,0,517750861,2012
14,2011-12-31 00:00:00,503037201,14711948,1712,0,0,517750861,2011
15,2010-12-31 00:00:00,503037201,14715976,1875,0,0,517755052,2010
16,2009-12-31 00:00:00,503037201,14715976,1875,0,0,517755052,2009
17,2008-12-31 00:00:00,503037201,14715976,1900,0,0,517755077,2008
18,2007-12-31 00:00:00,503037201,14715976,1970,0,0,517755147,2007
19,2006-12-31 00:00:00,503037201,14715976,3185,0,0,517756362,2006
20,2005-12-31 00:00:00,503155275,14601740,823,0,0,517757838,2005
21,2004-12-31 00:00:00,503407466,14349549,892,0,0,517757907,2004
22,2003-12-31 00:00:00,503560746,14196269,1888,0,0,517758903,2003
23,2002-12-31 00:00:00,504590694,13167813,1327,0,0,517759834,2002
24,2001-12-31 00:00:00,504742640,13015867,2693,0,0,517761200,2001
25,2000-12-31 00:00:00,504251545,13506962,2842,0,0,517761349,2000
26,1999-12-31 00:00:00,503482566,14275941,2928,0,0,517761435,1999
27,1998-12-31 00:00:00,382827285,14556222,3298,0,0,397386805,1998
28,1997-12-31 00:00:00,382775152,14608355,3431,0,0,397386938,1997
29,1996-12-31 00:00:00,384744599,14864453,3879,73955,0,399686886,1996
30,1995-12-31 00:00:00,417813172,14405073,388,0,0,432218633,1995
31,1994-12-31 00:00:00,484141987,14308088,1177,0,0,498451252,1994
32,1993-12-31 00:00:00,589474879,15058542,1416,0,0,604534837,1993
33,1992-12-31 00:00:00,700814858,15676897,1609,0,0,716493364,1992
34,1991-12-31 00:00:00,692274086,15834108,3181,0,0,708111375,1991
35,1990-12-31 00:00:00,814884742,18177209,3065,0,0,833065016,1990
36,1989-12-31 00:00:00,936094998,13177209,3307,0,0,949275514,1989
37,1988-12-31 00:00:00,984436413,18181740,483,0,0,1002618636,1988
38,1987-12-31 00:00:00,1043352428,18424324,7515,0,0,1061784267,1987
39,1986-12-31 00:00:00,1126881761,18799238,8463,0,0,1145689462,1986
40,1985-12-31 00:00:00,1362921566,26936217,10859,0,0,1389868642,1985
41,1984-12-31 00:00:00,1257194159,60731903,17422,0,0,1317943484,1984

=== 2. Part des titres dans le total ===

    annee      titres       total  part_titres_pct
0    2025   767434350   744790239            103.0
1    2024   724385541  1282490239             56.5
2    2023   724385541  2244991558             32.3
3    2022   724385541  2246911027             32.2
4    2021   724385541  2246915717             32.2
5    2020   724385541  2897920637             25.0
6    2019   732687201   747122696             98.1
7    2018   732687201   747127242             98.1
8    2017   732687201   747382781             98.0
9    2016   732687201   747396018             98.0
10   2015   503037201   517746018             97.2
11   2014   503037201   517746018             97.2
12   2013   503037201   517750861             97.2
13   2012   503037201   517750861             97.2
14   2011   503037201   517750861             97.2
15   2010   503037201   517755052             97.2
16   2009   503037201   517755052             97.2
17   2008   503037201   517755077             97.2
18   2007   503037201   517755147             97.2
19   2006   503037201   517756362             97.2
20   2005   503155275   517757838             97.2
21   2004   503407466   517757907             97.2
22   2003   503560746   517758903             97.3
23   2002   504590694   517759834             97.5
24   2001   504742640   517761200             97.5
25   2000   504251545   517761349             97.4
26   1999   503482566   517761435             97.2
27   1998   382827285   397386805             96.3
28   1997   382775152   397386938             96.3
29   1996   384744599   399686886             96.3
30   1995   417813172   432218633             96.7
31   1994   484141987   498451252             97.1
32   1993   589474879   604534837             97.5
33   1992   700814858   716493364             97.8
34   1991   692274086   708111375             97.8
35   1990   814884742   833065016             97.8
36   1989   936094998   949275514             98.6
37   1988   984436413  1002618636             98.2
38   1987  1043352428  1061784267             98.3
39   1986  1126881761  1145689462             98.4
40   1985  1362921566  1389868642             98.1
41   1984  1257194159  1317943484             95.4

=== 3. Les 3 années les plus récentes ===

   annee       total
0   2025   744790239
1   2024  1282490239
2   2023  2244991558

=== 4. Tri selon le compte n°1 (décroissant) ===

    annee    compte_1
0    2020  2173462451
1    2022  1522462451
2    2021  1522462451
3    2023  1519729540
4    2024   557629540
5    1984    60731903
6    1985    26936217
7    2025    19929540
8    1986    18799238
9    1987    18424324
10   1988    18181740
11   1990    18177209
12   1991    15834108
13   1992    15676897
14   1993    15058542
15   1996    14864453
16   2010    14715976
17   2009    14715976
18   2008    14715976
19   2007    14715976
20   2006    14715976
21   2013    14711948
22   2012    14711948
23   2011    14711948
24   2016    14700011
25   2015    14700011
26   2014    14700011
27   2017    14692637
28   1997    14608355
29   2005    14601740
30   1998    14556222
31   1995    14405073
32   2019    14360791
33   2018    14360791
34   2004    14349549
35   1994    14308088
36   1999    14275941
37   2003    14196269
38   2000    13506962
39   1989    13177209
40   2002    13167813
41   2001    13015867

=== 5. Années où le total est inférieur à 600 millions de DTS ===

    annee      total
0    1994  498451252
1    1995  432218633
2    1996  399686886
3    1997  397386938
4    1998  397386805
5    1999  517761435
6    2000  517761349
7    2001  517761200
8    2002  517759834
9    2003  517758903
10   2004  517757907
11   2005  517757838
12   2006  517756362
13   2007  517755147
14   2008  517755077
15   2009  517755052
16   2010  517755052
17   2011  517750861
18   2012  517750861
19   2013  517750861
20   2014  517746018
21   2015  517746018

=== 6. Nombre d'années avec un total > 1 milliard de DTS ===

   nb_annees
0         10

=== 7. Moyenne des titres depuis 2010 ===

   moyenne_titres
0     646145879.0

=== 8. Minimum et maximum des titres ===

   min_titres  max_titres
0   382775152  1362921566

=== 9. Moyenne du total par période de 5 ans ===

   debut_periode  nb_annees   total_moyen
0           1980          1  1.317943e+09
1           1985          5  1.109847e+09
2           1990          5  6.721312e+08
3           1995          5  4.288881e+08
4           2000          5  5.177598e+08
5           2005          5  5.177559e+08
6           2010          5  5.177507e+08
7           2015          5  7.013550e+08
8           2020          5  2.183846e+09
9           2025          1  7.447902e+08

=== 10. Périodes de 5 ans où le compte n°1 a dépassé 1 milliard ===

   debut_periode  max_compte_1
0           2020    2173462451

=== 11. AND : depuis 2000 et total inférieur à 600 millions ===

    annee      total
0    2000  517761349
1    2001  517761200
2    2002  517759834
3    2003  517758903
4    2004  517757907
5    2005  517757838
6    2006  517756362
7    2007  517755147
8    2008  517755077
9    2009  517755052
10   2010  517755052
11   2011  517750861
12   2012  517750861
13   2013  517750861
14   2014  517746018
15   2015  517746018

=== 11. OR : total > 2 milliards OU compte CVA négatif ===

   annee       cva       total
0   2020         0  2897920637
1   2021         0  2246915717
2   2022         0  2246911027
3   2023         0  2244991558
4   2025 -43048809   744790239

=== 12. BETWEEN : période 2015-2019 ===

   annee      total
0   2015  517746018
1   2016  747396018
2   2017  747382781
3   2018  747127242
4   2019  747122696

=== 12. IN : années choisies ===

   annee       total
0   1987  1061784267
1   1998   397386805
2   2008   517755077
3   2020  2897920637
4   2025   744790239

=== 13. Classement des 8 plus hauts niveaux du compte n°1 ===

   annee    compte_1  rang
0   2020  2173462451     1
1   2022  1522462451     2
2   2021  1522462451     2
3   2023  1519729540     4
4   2024   557629540     5
5   1984    60731903     6
6   1985    26936217     7
7   2025    19929540     8

=== 14. Années où le total est sous la moyenne ===

    annee      total
0    1990  833065016
1    1991  708111375
2    1992  716493364
3    1993  604534837
4    1994  498451252
5    1995  432218633
6    1996  399686886
7    1997  397386938
8    1998  397386805
9    1999  517761435
10   2000  517761349
11   2001  517761200
12   2002  517759834
13   2003  517758903
14   2004  517757907
15   2005  517757838
16   2006  517756362
17   2007  517755147
18   2008  517755077
19   2009  517755052
20   2010  517755052
21   2011  517750861
22   2012  517750861
23   2013  517750861
24   2014  517746018
25   2015  517746018
26   2016  747396018
27   2017  747382781
28   2018  747127242
29   2019  747122696
30   2025  744790239

=== 15. Synthèse : tendance du total d'une année à l'autre ===

    annee       total     variation tendance
0    2025   744790239 -5.377000e+08   Baisse
1    2024  1282490239 -9.625013e+08   Baisse
2    2023  2244991558 -1.919469e+06   Baisse
3    2022  2246911027 -4.690000e+03   Baisse
4    2021  2246915717 -6.510049e+08   Baisse
5    2020  2897920637  2.150798e+09   Hausse
6    2019   747122696 -4.546000e+03   Baisse
7    2018   747127242 -2.555390e+05   Baisse
8    2017   747382781 -1.323700e+04   Baisse
9    2016   747396018  2.296500e+08   Hausse
10   2015   517746018  0.000000e+00   Stable
11   2014   517746018 -4.843000e+03   Baisse
12   2013   517750861  0.000000e+00   Stable
13   2012   517750861  0.000000e+00   Stable
14   2011   517750861 -4.191000e+03   Baisse
15   2010   517755052  0.000000e+00   Stable
16   2009   517755052 -2.500000e+01   Baisse
17   2008   517755077 -7.000000e+01   Baisse
18   2007   517755147 -1.215000e+03   Baisse
19   2006   517756362 -1.476000e+03   Baisse
20   2005   517757838 -6.900000e+01   Baisse
21   2004   517757907 -9.960000e+02   Baisse
22   2003   517758903 -9.310000e+02   Baisse
23   2002   517759834 -1.366000e+03   Baisse
24   2001   517761200 -1.490000e+02   Baisse
25   2000   517761349 -8.600000e+01   Baisse
26   1999   517761435  1.203746e+08   Hausse
27   1998   397386805 -1.330000e+02   Baisse
28   1997   397386938 -2.299948e+06   Baisse
29   1996   399686886 -3.253175e+07   Baisse
30   1995   432218633 -6.623262e+07   Baisse
31   1994   498451252 -1.060836e+08   Baisse
32   1993   604534837 -1.119585e+08   Baisse
33   1992   716493364  8.381989e+06   Hausse
34   1991   708111375 -1.249536e+08   Baisse
35   1990   833065016 -1.162105e+08   Baisse
36   1989   949275514 -5.334312e+07   Baisse
37   1988  1002618636 -5.916563e+07   Baisse
38   1987  1061784267 -8.390520e+07   Baisse
39   1986  1145689462 -2.441792e+08   Baisse
40   1985  1389868642  7.192516e+07   Hausse
41   1984  1317943484           NaN   Départ